apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: argocd-notifications-controller-policy
spec:
  privileged: false  # Don't allow privileged pods!
  allowedCapabilities:
  - NET_ADMIN
  - NET_RAW
  - NET_BIND_SERVICE
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  volumes:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-notifications-controller-role
  namespace: argocd
rules:
- apiGroups: ['policy','extensions']
  resources: [podsecuritypolicies]
  verbs: [use]
  resourceNames: [argocd-notifications-controller-policy]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-notifications-controller-role-binding
  namespace: argocd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-notifications-controller-role
subjects:
- kind: ServiceAccount
  name: argocd-notifications-controller
