apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: rollouts-deployment
  name: rollouts-deployment
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rollouts-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rollouts-deployment
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
