name: get-build-args with semantic release

# Runs on all pushes to master and development
on: [push]

# use templated build workflow from master branch
jobs:
  set-build-args:
    name: "set-build-args"
    runs-on: ubuntu-latest
    outputs:
      build_args_encrypted: ${{ steps.set_build_args.outputs.build_args_encrypted }}
    steps:
      - name: set build-args
        id: set_build_args
        shell: bash
        run: |
          build_args="GITHUB_NPM_PAT=${{secrets.READ_PAT}}"
          echo $build_args
          echo "::add-mask::$build_args"
          build_args_encrypted=$(gpg --symmetric --batch --passphrase "${{secrets.READ_PAT}}" --output - <(echo "$build_args") | base64 -w0)
          echo "build_args_encrypted=$build_args_encrypted" >> $GITHUB_OUTPUT

  publish:
    uses: HanssenKai/testRepo/.github/workflows/workflow.yaml@main
    needs: set-build-args
    secrets: inherit
    with:
      build-args-encrypted: ${{needs.set-build-args.outputs.build_args_encrypted}}
