name: publish with semantic release

# Runs on all pushes to master and development
on: [push]

# use templated build workflow from master branch
jobs:
  publish:
    uses: HanssenKai/testRepo/.github/workflows/workflow.yaml@master
    secrets: inherit
    with:
      build-args:
        - args1
        - args2
        #- GITHUB_NPM_PAT=${{secrets.READ_PAT}} 
    


