name: publish with semantic release

# Runs on all pushes to master and development
on: [push]

env:
  SECRET: ${{secrets.READ_PAT}}
# use templated build workflow from master branch
jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
    - id: step1
      run: echo "test=hello" >> $GITHUB_OUTPUT
  publish:
    uses: HanssenKai/testRepo/.github/workflows/workflow.yaml@main
    needs: job1
    secrets: inherit
    with:
      #build-args: "${{'${{secrets.READ_PAT}}'}}"
      #build-args: ${{'TEST=${{secrets.READ_PAT}'}}
      build-args: ${{needs.job1.outputs.output1}}
        #- GITHUB_NPM_PAT=${{secrets.READ_PAT}} 
