name: publish with semantic release

# Runs on all pushes to master and development
on: [push]

# use templated build workflow from master branch
jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      build-args: ${{ steps.step1.outputs.test }}
    steps:
    - name: Set outputs
      id: set_outputs
      shell: bash
      run: |
        build-args="test=${{secrets.READ_PAT}}
        build-args-encrypted=$(gpg --symmetric --batch --passphrase "$SECRET" --output - <(echo "$build-args") | base64 -w0)
        echo "::set-output name=build-args::$build-args-encrypted"
      env:
        SECRET: ${{ secrets.READ_PAT }}
  get-output:
    runs-on: ubuntu-latest
    needs: set_outputs
  #publish:
  #  uses: HanssenKai/testRepo/.github/workflows/workflow.yaml@main
  #  needs: set_outputs
  #  secrets: inherit
  #  with:
  #    #build-args: "${{'${{secrets.READ_PAT}}'}}"
  #    #build-args: ${{'TEST=${{secrets.READ_PAT}'}}
  #    build-args: ${{needs.job1.outputs.output1}}
  #      #- GITHUB_NPM_PAT=${{secrets.READ_PAT}} 
