name: publish with semantic release

# Runs on all pushes to master and development
on: [push]

# use templated build workflow from master branch
jobs:
  publish:
    uses: HanssenKai/testRepo/.github/workflows/workflow.yaml@main
    secrets: inherit
    with:
      build-args: "string1"
        #- GITHUB_NPM_PAT=${{secrets.READ_PAT}} 
