name: semantic release

# publishes a image based on semantic versioning

on:
  workflow_call: # only run when called from another workflow
    inputs:
      build-args:
        required: true
        type: string
      


env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest 
    permissions:
      contents: write
      packages: write
    steps:
      - name: "get-build-args"
        id: get_deploy_key
        shell: bash
        run: |
          build_args=$(gpg --decrypt --quiet --batch --passphrase "${{secrets.READ_PAT}}" --output - <(echo "${{ needs.set-build-args.outputs.build_args_encrypted }}" | base64 --decode))
          echo "$build_args"
          echo "::add-mask::$build_args"
          echo "build_args=$build_args" >> $GITHUB_OUTPUT

          # Uses ${{ steps.get_deploy_key.outputs.build_args }} later...

      - name: echo
        run: |
          echo "${{inputs.build-args}}"
      - name: echo sec
        run: |
          echo ${{secrets.READ_PAT}}
      - name: echo step
        run: |
          echo ${{steps.get_deploy_key.outputs.build_args}}
      #- name: Checkout repository
      #  uses: actions/checkout@v3
      #
      #- name: Set up Docker Buildx
      #  uses: docker/setup-buildx-action@v2
      #
      #- name: Log in to the Container registry
      #  uses: docker/login-action@v2
      #  with:
      #    registry: ${{ env.REGISTRY }}
      #    username: ${{ github.actor }}
      #    password: ${{ secrets.GITHUB_TOKEN }}
      #  
      #
      #- name: Build and push Docker image
      #  uses: docker/build-push-action@v3
      #  with:
      #    context: .
      #    push: true
      #    tags: ${{env.REGISTRY}}/${{env.IMAGE_NAME}}:${{ needs.semantic-release.outputs.version }}
      #    #build-args: GITHUB_NPM_PAT=${{secrets.READ_PAT}}
      #    build-args: ${{ inputs.build-args }}
      #    cache-from: type=gha
      #    cache-to: type=gha,mode=max


